import {experienceFixtures,makeResponse} from './fixtures';
import {uxScenarios} from './scenarios';
export type ReviewScenario = {id:string;label:string;group:'Counselling'|'Boxes & inputs'|'Waiting & recovery';request:string;expected:string;response?:any;phase?:'waiting'|'thinking'|'receiving'|'checking';state?:'slow'|'stopped'|'invalid'|'earlier';issue?:string};
const b=(type:string,title:string,text='',items:any[]=[],data?:any)=>({id:type,type,level:type==='heading'?'h2':'none',variant:'default',title,text,items,columns:[],rows:[],...(data?{data}:{})});
const item=(id:string,title:string,text:string,status='')=>({id,title,text,status,value:''});
const q=(text:string)=>({...makeResponse().interaction,kind:'question',input_type:'text',question_id:'review-question',question:text});
const action=(label:string,message:string)=>({...makeResponse().interaction,recommended_actions:[{id:'review-next',label,message}]});
const designed:Record<string,[string,string?]> = {
'school-undecided':['You do not need a career choice yet. Try a ten-minute activity, such as sketching an idea, organising something or solving a puzzle. Notice what you enjoy.','Which of those feels easiest to try?'],
'current-student':['Before leaving your course, try a small outdoor activity and ask your course adviser what options would preserve your progress. You can explore without making a final decision.','What appeals to you about working outdoors?'],
'near-completion':['Start with one practical task related to your diploma. A placement may be part of study; an internship is work experience; an entry-level job is employment. Check duties, supervision and payment before agreeing.','What is your diploma in?'],
'graduate':['Choose one recent application. Compare your examples with the job’s requirements and improve one example so it shows what you did and the result.','Which requirement is hardest to demonstrate?'],
'first-job':['You can start with experience from school, home or volunteering. Describe one task you have actually done; we can look for evidence you could use in an application.','What is one task you have helped with?'],
'basic-experience':['Your retail experience gives us a starting point. “Steadier” could mean regular hours, more income or staying longer with one employer.','Which of those matters most?'],
'new-field':['Try learning about the everyday tasks first, then look for a supervised way to experience them. Check any training, safety or supervision requirements before committing.','Which part of animal care interests you?'],
'experienced-change':['Your years in logistics are useful context, but the tasks you performed tell us more about transferable skills. We can connect a real example to work in another field.','What is one logistics task you handled regularly?'],
'same-field':['Start by updating one recent work example and the hours you can offer. Then use those details to assess a suitable hospitality vacancy.','What kind of hospitality work do you want to continue?'],
'employed-change':['A gradual move can let you test new tasks while keeping your income. Retraining may build a specific skill, but cost and workload need checking. Neither route guarantees a job.','What type of work would you like to try?'],
'upskill':['Pick one spreadsheet task you already do, such as sorting records or checking totals. Practise it on sample data and check the result before using it at work.','Which task would you like to make easier?'],
'leadership':['Try a small, agreed responsibility such as coordinating one task, then ask for feedback. This gives you evidence of how you support people before taking on a management role.','Is there a small team task you could help coordinate?'],
'lateral':['A move to customer success could use some of your sales experience, depending on the actual duties. Compare customer follow-up, problem-solving and product knowledge against a real role description.','Which of those tasks have you done?'],
'job-preparation':['Choose two examples of work you have done. Practise explaining the situation, your action and the result. Then prepare one question about the role.','Which interview question would you like to practise?'],
'return-to-work':['Let’s use the school hours you said are available and your need for income. Start with roles whose advertised shifts fit, then check the actual schedule. Caring experience can provide examples, but we should describe what you did.','What kind of work would you like to return to?'],
'reduced-hours':['You want to keep working with fewer hours. You could explore reduced hours in your current role or compare roles with a suitable schedule. Availability and income will need checking.','How many hours would you like to work?'],
'specialist':['Start by identifying the electric vehicle tasks you want to perform, then check the training, supervision and safety requirements for those tasks. Your mechanic experience is relevant but does not establish every new competency.','Which task do you want to learn first?'],
'new-subject':['For enjoyment, start with one photo exercise: photograph the same object from three angles and choose the result you like. You do not need a career plan or a course to try this.'],
'business':['Write down one person’s problem your idea could solve. Ask a few potential customers how they handle it now before spending money. Their feedback can help you refine a small test.','What idea would you like to test?'],
'staff':['Pick one customer situation your three staff find difficult. Practise a response together and agree what a good result looks like. Review what changed after a week.','Which situation should the team practise?'],
'parent-child':['Your preference for nursing and your daughter’s interest in design are different starting points. Give her room to describe what she enjoys, then explore small activities in both areas without committing her.','What does she enjoy about design?'],
'access':['Let’s keep the plan within your three available hours and look for captioned materials. Start with a short sample lesson. Ask the provider to confirm captions and any live attendance before enrolling.','What would you like to learn?'],
'simple':['An apprenticeship combines paid work with training for a job. You learn by doing tasks at work and studying. The details depend on the apprenticeship.'],
'compare':['Compare the same factors for each route: time, cost, what you can try and what still needs checking. Keep your current job in the plan.'],
'plan':['Week 1: practise recording sample transactions. Week 2: sort them into categories. Week 3: check totals and fix errors. Week 4: review a small sample ledger and decide whether you want to learn more. Keep each week within five hours; use sample data.'],
'handoff':['We can prepare a draft describing the cybersecurity training you want. Nothing will be sent. Location and your declared study category help prepare the request; they do not confirm eligibility.'],
'outside-au':['You have said Auckland, New Zealand. I cannot submit a provider request here or assume Australian eligibility. We can prepare questions to help you explore local training.','What subject would you like to study?'],
'rpl':['Recognition of prior learning means a provider assesses evidence of what you already know and can do against a qualification’s requirements. Experience alone does not automatically give you a certificate.','What construction tasks could you show evidence for?'],
'paid-work-training':['An apprenticeship combines employment with training. A course focuses on learning and may include practical work. An internship offers work experience; payment and conditions need checking for the specific opportunity.'],
'unavailable-service':['I cannot book appointments or send reminders from this lab. You can contact a counsellor directly and add a reminder to your calendar. I can help you prepare a short message.'],
'job-request':['We can draft the kind of administrative work you want to explore. Nothing will be sent and no application will be made.','Where would you like to work?'],
'apprentice-request':['We can draft your interest in an electrical apprenticeship, which combines work and training. An employer and training provider would need to confirm openings and requirements. Nothing will be submitted.','Where would you like to work and train?'],
'trainee-request':['We can draft a business administration traineeship request. The work, training, entry requirements and availability will need confirmation. Nothing will be sent.','Where would you like to work and train?'],
'intern-request':['We can prepare a marketing internship draft. Payment, supervision and course credit need checking for each opportunity. Nothing will be sent.','What practical marketing tasks would you like to try?'],
'placement-request':['Your course requires a community services placement. Start with the course’s placement rules, required hours and supervision requirements so the draft describes the right experience. Nothing will be sent.','What placement requirements has your course provided?'],
'grad-request':['We can draft your interest in engineering graduate programs. Each program has its own entry rules and dates, which need checking. We will not apply anywhere.','Which engineering area would you like to explore?'],
'rpl-request':['A hospitality prior-learning draft can describe tasks you have performed and evidence you hold. A provider must assess that evidence; credit is not automatic. Nothing will be sent.','Which hospitality tasks could you demonstrate?'],
'pathway-request':['Start with an office task you could practise while keeping your retail work. Use a real example to identify what transfers, practise one gap and review your progress before choosing training.','Which office task interests you?'],
'admission-request':['I cannot enrol you or confirm admission here. The provider must check its requirements and accept your application. I can help you prepare the questions or information you need.'],
'residency-unsure':['You do not need to guess or share documents here. We can pause that part of the draft and continue exploring. Ask the provider which study category applies when you are ready.']
};
const counselling:ReviewScenario[]=uxScenarios.map(([id,label,goal,request,expected])=>{
 const [answer,question]=designed[id];
 let response=makeResponse({content_blocks:[b('text','',answer)],interaction:question?q(question):makeResponse().interaction});
 if(id==='compare')response=experienceFixtures.find(f=>f.id==='compare')!.response;
 if(id==='handoff')response=experienceFixtures.find(f=>f.id==='location')!.response;
 if(id==='plan')response=makeResponse({content_blocks:[{...b('text','','Here is a small trial you can review before choosing a course.'),id:'intro'},b('steps','A four-week trial','Use sample data. Allow no more than five hours each week.',[
 item('one','Week 1 · Record','Enter five sample transactions. Keep a clear record.','current'),item('two','Week 2 · Sort','Group transactions and explain your categories.','next'),item('three','Week 3 · Check','Check totals and record any corrections.','next'),item('four','Week 4 · Decide','Review your sample ledger. Note what you enjoyed and what was difficult.','next')])],interaction:action('Review my trial','Help me review what I learned from my bookkeeping trial.')});
 return {id,label,group:'Counselling',request,expected:goal+'. '+expected,response};
});
const layout=(id:string,label:string,block:any,expected:string,rich=false):ReviewScenario=>({id:'box-'+id,label,group:'Boxes & inputs',request:'Show '+label.toLowerCase()+'.',expected,response:makeResponse({schema_version:rich?'1.4':'1.3',...(rich?{rmo_readiness:{...makeResponse().rmo_readiness,verification_required:[]},state:{...makeResponse().state,progress:{explained:[],failed_attempts:0,loop_count_same_issue:0}}}:{}),content_blocks:[...(block.type!=='text'||block.title?[{...b('text','','Here is an example to help you consider your next step.'),id:'intro',...(rich?{data:{}}:{})}]:[]),{...block,...(rich?{data:block.data||{}}:{})}]})});
const formats:ReviewScenario[]=[
 layout('heading','Section heading',b('heading','Your next step','A small start'),'Readable heading; no repeated title.'),
 layout('text','Direct answer',b('text','','Could you confirm whether this unit has compulsory live sessions, and when they run?'),'When asked for one question, deliver one question without adding another form.'),
 layout('list','Short list',b('list','Before you decide','',[item('a','Time','Check scheduled attendance.'),item('b','Cost','Check the full cost.'),item('c','Support','Ask about the support you need.')]),'Three distinct checks; no implied confirmation.'),
 layout('steps','Action plan',b('steps','Try, review, decide','',[item('a','Try one task','Spend 20 minutes on sample data.','current'),item('b','Review','Note what you enjoyed.','next'),item('c','Decide','Choose whether to continue.','next')]),'Sequence, effort and a decision point; a plan is not proof of completion.'),
 layout('table','Facts with gaps',{...b('table','What we know'),columns:[{key:'factor',label:'Detail'},{key:'value',label:'Information'}],rows:[{id:'a',cells:[{key:'factor',value:'Available study time'},{key:'value',value:'12 hours per week · You told us'}]},{id:'b',cells:[{key:'factor',value:'Required attendance'},{key:'value',value:''}]}]},'Missing information reads “Not provided”; columns remain labelled on a phone.'),
 {...experienceFixtures.find(f=>f.id==='compare')!,id:'box-comparison',group:'Boxes & inputs',request:'Compare three routes.',expected:'Same criteria for every option; no dropped columns.'},
 layout('key_value','Personal summary',b('key_value','Details you gave us','',[{...item('a','Location','Geelong, Victoria'),value:'Geelong, Victoria'},{...item('b','Availability','12 hours each week, with evenings unavailable'),value:'12 hours each week, with evenings unavailable'}]),'Long values wrap; no inferred availability.'),
 ...['default','info','success','warning','danger','muted'].map(variant=>layout('callout-'+variant,'Notice · '+variant,{...b('callout',variant==='success'?'Detail updated':'Before you commit',variant==='success'?'Your draft now says 12 hours per week. Nothing has been sent.':'Course attendance has not been confirmed. Check the current unit guide or ask the provider.'),variant},'Meaning is expressed in words, not colour alone.')),
 layout('cards','Two route cards',b('cards','Two ways to try', 'Illustrative routes; availability is not checked.',[],{cards:['Guided learning','Independent practice'].map((title,i)=>({id:'c'+i,title,subtitle:'A way to explore',description:i?'Practise a small task at your own pace.':'Try a sample lesson with feedback.',status:'neutral',badge:'Example',facts:[{label:'Time',value:'Choose a short trial'},{label:'Before committing',value:'Check cost and support'}]}))}),'Cards share the same facts and remain readable on a phone.',true),
 layout('timeline','Timeline',b('timeline','A suggested sequence','',[],{milestones:['Try a task','Review your experience','Decide the next step'].map((label,i)=>({id:'m'+i,label,description:'Adjust this plan to suit your week.',time_label:'Step '+(i+1),status:i?'upcoming':'current',optional:false}))}),'No invented dates or completed bookings.',true),
 layout('flow','Decision branches',b('flow','Choose based on what you learn','',[],{nodes:[{id:'node_a',label:'Try a small task',description:'Notice your interest and effort.',node_type:'experience',status:'current'},{id:'node_b',label:'Explore training',description:'Check the gap you want to learn.',node_type:'training',status:'upcoming'}],edges:[{from:'node_a',to:'node_b',label:'If you want to continue',condition:'After reviewing the trial'}]}),'Connections show human-readable step names, never internal IDs.',true),
 layout('pathway','Alternative pathways',b('pathway_map','Possible next steps','',[],{goal:'Explore administration while working',lanes:[{id:'l1',title:'Practise first',summary:'A small commitment',recommended:false,steps:[{id:'s1',label:'Try a spreadsheet task',description:'Use sample data.',status:'current'}]},{id:'l2',title:'Ask about a short course',summary:'Check whether it meets your gap',recommended:false,steps:[{id:'s2',label:'Check content and attendance',description:'Ask the provider.',status:'upcoming'}]}]}),'Alternatives have trade-offs; no automatic preferred route.',true),
 layout('scorecard','Numbers with context',b('scorecard','Your planning figures','',[],{metrics:[{id:'hours',label:'Time you offered',value:12,value_type:'number',unit:'hours/week',max:null,status:'neutral',trend:'unknown',description:'User-provided. Does not establish that the course fits.'},{id:'fit',label:'Course fit',value:'Not checked',value_type:'text',unit:'',max:null,status:'neutral',trend:'unknown',description:'Attendance and peak workload still need checking.'}]}),'A stated number is not a suitability score or a success probability.',true),
 ...['bar','line','donut','funnel'].map(chart_type=>layout('chart-'+chart_type,'Data · '+chart_type,b('chart','Two trial weeks','Illustrative user-entered figures, not course workload advice.',[],{chart_type,categories:['Week 1','Week 2'],series:[{id:'planned',label:'Planned',values:[3,4],unit:'hours'},{id:'actual',label:'Used',values:[0,2],unit:'hours'}],source_status:'provided'}),'Every series, unit and zero is visible. A labelled table is used for reliable comparison.',true)),
 layout('progress','Plan progress',b('progress','Your plan','',[],{stages:[{id:'p1',label:'Describe what matters',status:'completed',description:'Recorded in this draft.'},{id:'p2',label:'Check the details',status:'current',description:'Attendance still needs confirming.'},{id:'p3',label:'Decide whether to proceed',status:'upcoming',description:'No provider request has been sent.'}]}),'Labels and explanations remain readable; progress refers to the plan, not external execution.',true),
 ...experienceFixtures.filter(f=>!['compare'].includes(f.id)).map(f=>({...f,id:'input-'+f.id,group:'Boxes & inputs' as const,request:'Try this question.',expected:'Enter an answer, submit once, and test a failed reply. A failed reply must preserve the answer.'}))
];
const edgeCases:ReviewScenario[]=[
 {id:'missing-data',label:'Not enough evidence',group:'Counselling',request:'Does this course fit my 12 available hours?',expected:'Do not turn a workload estimate into a fit verdict. Identify the missing fact and offer research.',response:makeResponse({content_blocks:[b('text','','You have 12 hours available each week. I cannot confirm that this course fits without its scheduled attendance and expected workload, including assessments.'),{...b('callout','What still needs checking','The current unit guide, compulsory sessions and peak assessment weeks.'),variant:'warning'}],interaction:action('Check attendance','Help me find current attendance requirements for this course.')})},
 {id:'conflicting-data',label:'Sources disagree',group:'Counselling',request:'One page says online and another says campus. Which is right?',expected:'Show the disagreement and relevant scope; no invented resolution.',response:makeResponse({content_blocks:[b('text','','Those descriptions may refer to different units, intakes or delivery modes. We have not established which applies to your choice.'),{...b('callout','Before deciding','Check the exact course, unit, intake and campus with the provider.'),variant:'warning'}],interaction:q('Which course and intake are you checking?')})},
 {id:'changed-detail',label:'User corrects availability',group:'Counselling',request:'I can study 6 hours, not 12. Keep evenings free.',expected:'Replace the old constraint, preserve the rest and reconsider the plan.',response:makeResponse({content_blocks:[b('text','','I have updated the plan to six hours per week, with evenings unavailable. The earlier 12-hour assumption no longer applies. We should check workload against your updated limit before choosing a study load.')],interaction:action('Recheck the plan','Review the plan using six hours per week and no evenings.')})},
 {id:'no-more-questions',label:'User asks to stop questions',group:'Counselling',request:'Give me just one question to ask the provider. No follow-up.',expected:'One requested sentence, no intake question or extra action.',response:makeResponse({content_blocks:[b('text','','Does this unit require live attendance, and if so, on which days and at what times?')]})},
 {id:'pause',label:'Pause or change direction',group:'Counselling',request:'Stop the course request. I only want to explore.',expected:'End the intake; do not keep asking for location or residency.',response:makeResponse({response_intent:'PAUSE_CLOSURE',content_blocks:[b('text','','The draft request is paused. Nothing has been sent. You can explore another direction whenever you are ready.')]})}
];
const lifecycle:ReviewScenario[]=[
 ...(['waiting','thinking','receiving','checking'] as const).map(phase=>({id:'state-'+phase,label:phase==='thinking'?'Considering the question':phase==='receiving'?'Receiving the answer':phase==='checking'?'Checking display format':'Waiting for Gemini',group:'Waiting & recovery' as const,request:'Send a question.',expected:'Compact rotating title, short subtext and Stop. No raw reasoning or unfinished JSON.',phase})),
 {id:'state-slow',label:'Slow response',group:'Waiting & recovery',request:'The response takes longer.',expected:'Explain the delay; keep Stop available without claiming fake progress.',phase:'waiting',state:'slow'},
 {id:'state-stopped',label:'Stopped response',group:'Waiting & recovery',request:'Stop generation.',expected:'Keep the question draft; offer retry. Do not treat partial JSON as a final answer.',state:'stopped'},
 {id:'state-invalid',label:'Invalid / unsupported output',group:'Waiting & recovery',request:'The model returns an unsupported shape.',expected:'Show a plain error and retry; never expose JSON. Checklist blocks are currently outside both supported schemas.',state:'invalid'},
 {id:'state-earlier',label:'Earlier question',group:'Waiting & recovery',request:'Scroll back to an older question.',expected:'Show the earlier question without active stale inputs.',state:'earlier',response:experienceFixtures.find(f=>f.id==='single')!.response}
];
export const outputReviewScenarios:ReviewScenario[]=[...counselling,...edgeCases,...formats,...lifecycle];
export const outputReviewIssues=[
 {status:'Fixed',title:'Charts silently omitted extra series',detail:'All chart formats now display every series, category, unit and zero in a labelled table.'},
 {status:'Fixed',title:'Rich content was missing from copy and speech',detail:'The readable projection now includes card facts, pathways, timelines, metrics and chart data.'},
 {status:'Fixed',title:'Flow connections exposed internal IDs',detail:'Connections now use the visible step names.'},
 {status:'Fixed',title:'Dense cards used very small text',detail:'Rich layouts now use larger text, wrap long values and keep progress explanations in a vertical list.'},
 {status:'Partly improved',title:'A polished answer can contain unverified advice',detail:'A focused Gemini retest respected the one-question request and stopped claiming that 12 study hours fit a unit. Accessibility advice still implied short modules prevent overload without workload evidence. This remains open.'},
 {status:'Known limit',title:'No proof of provider eligibility or course suitability',detail:'Schema validation checks the output format. It does not verify advice. Explore more has separate sourced research; automatic evidence checks for every main-chat recommendation are not yet connected.'},
 {status:'Known limit',title:'Checklist is not an accepted output type',detail:'A dormant renderer showed every item with a tick. The fallback is corrected, but the main contract still rejects this type. Use a list or steps.'},
 {status:'Needs user testing',title:'Readability across ages is not yet proven',detail:'Phone layout and interactions can be checked here. Comprehension needs sessions with younger users, adults, parents and people with access needs.'},
 {status:'Known limit',title:'Provider actions are draft-only',detail:'Forms and buttons cannot book, enrol, submit an application or establish an entitlement.'}
];
