package com.yuzee.tokenlab.model;

public enum MemoryType {
    PROFILE_FACT,
    PREFERENCE,
    GOAL,
    CONSTRAINT,
    QUALIFICATION,
    ACADEMIC_RESULT,
    CAREER_INTEREST,
    CAREER_REJECTION,
    DECISION,
    PLAN,
    MILESTONE,
    DEADLINE,
    LOCATION_PREFERENCE,
    FINANCIAL_CONSTRAINT,
    UNCERTAINTY,
    OPEN_QUESTION,
    ADVISOR_RECOMMENDATION
}
