import { applyPresentationDefaults } from "../src/protocol/presentationDefaults";
import assert from 'node:assert/strict';
import { renderToStaticMarkup } from 'react-dom/server';
import React from 'react';
import { experienceFixtures, makeResponse } from '../src/ux/fixtures';
import { validateProtocol, validateInteractionFields, validateUserEventAgainstActiveInteraction } from '../src/protocol/validator';
import { acceptedResponse, responseToReadableText } from '../src/ux/responsePresentation';
import { ProtocolInteraction } from '../src/components/ProtocolInteraction';
import { ProtocolV13Renderer } from '../src/components/ProtocolV13Renderer';
let checks=0;
function test(name:string,fn:()=>void){fn();checks++;console.log('PASS:',name);}
const get=(id:string)=>structuredClone(experienceFixtures.find(f=>f.id===id)!.response);
const event=(q:any, values:any)=>({userEvent:{interaction:{question_id:q.question_id,...values}}} as any);
for(const f of experienceFixtures) test(`Valid and renderable ${f.id}`,()=>{assert.equal(validateProtocol(f.response).protocolAccepted,true,JSON.stringify(validateProtocol(f.response).errors));assert.match(renderToStaticMarkup(React.createElement(ProtocolV13Renderer,{data:f.response})),/./);});
test('Unknown schema rejected',()=>assert.equal(acceptedResponse({...makeResponse(),schema_version:'9.9'}),null));
test('Null block fails safely',()=>assert.equal(acceptedResponse({...makeResponse(),content_blocks:[null]}),null));
test('Missing required root is rejected',()=>{const r=makeResponse();delete r.state;assert.equal(acceptedResponse(r),null);});
test('Location renders as typed input, not choices',()=>{const html=renderToStaticMarkup(React.createElement(ProtocolInteraction,{interaction:get('location').interaction,onInteract:async()=>true}));assert.match(html,/type="text"/);assert.match(html,/Type your suburb, town or postcode/);assert.equal((html.match(/<select/g)||[]).length,1);});
test('Blank required fields have individual errors',()=>{const c=validateInteractionFields(get('location').interaction,{location:'  ',residency:''});assert.equal(c.valid,false);assert.ok(c.fieldErrors.location&&c.fieldErrors.residency);});
test('Typed location and declared residency accepted',()=>assert.equal(validateInteractionFields(get('location').interaction,{location:'Geelong VIC 3220',residency:'Domestic'}).valid,true));
test('Outside-Australia location remains user entered',()=>assert.equal(validateInteractionFields(get('location').interaction,{location:'Auckland, New Zealand',residency:'International'}).valid,true));
test('Unknown field and invented residency rejected',()=>assert.equal(validateInteractionFields(get('location').interaction,{location:'Geelong',residency:'guaranteed',passport:'123'}).valid,false));
test('Oversized field rejected',()=>assert.equal(validateInteractionFields(get('location').interaction,{location:'x'.repeat(501),residency:'Domestic'}).valid,false));
test('Option IDs unique in output',()=>{const r=get('single');r.interaction.options[1].id=r.interaction.options[0].id;assert.equal(validateProtocol(r).protocolAccepted,false);});
test('Wrong question ID is rejected',()=>{const q=get('single').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event({...q,question_id:'old'},{selected_option_ids:['explore']}),q).valid,false);});
test('Invented selection rejected',()=>{const q=get('single').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event(q,{selected_option_ids:['invented']}),q).valid,false);});
test('Selection must have correct shape',()=>{const q=get('single').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event(q,{selected_option_ids:'explore'}),q).valid,false);});
test('Single select accepts one, rejects two',()=>{const q=get('single').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event(q,{selected_option_ids:['explore']}),q).valid,true);assert.equal(validateUserEventAgainstActiveInteraction(event(q,{selected_option_ids:['explore','learn']}),q).valid,false);});
test('Single select accepts permitted own answer',()=>{const q=get('single').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event(q,{self_input:'Something else'}),q).valid,true);});
test('Multi-select must not be empty',()=>{const q=get('multi').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event(q,{selected_option_ids:[]}),q).valid,false);assert.equal(validateUserEventAgainstActiveInteraction(event(q,{selected_option_ids:['hours','cost'],self_input:'Evenings'}),q).valid,true);});
test('Ranked order preserves every ID without duplicates',()=>{const q=get('rank').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event(q,{ranked_option_ids:['hours','income','interest']}),q).valid,true);assert.equal(validateUserEventAgainstActiveInteraction(event(q,{ranked_option_ids:['hours','hours','interest']}),q).valid,false);});
test('Text answer accepts uncertainty and rejects empty',()=>{const q=get('text').interaction;assert.equal(validateUserEventAgainstActiveInteraction(event(q,{self_input:'I am not sure'}),q).valid,true);assert.equal(validateUserEventAgainstActiveInteraction(event(q,{self_input:'  '}),q).valid,false);});
test('Suggested next message works with no active question',()=>assert.equal(validateUserEventAgainstActiveInteraction(undefined,null).valid,true));
test('Retired question cannot be answered',()=>assert.equal(validateUserEventAgainstActiveInteraction(event(get('single').interaction,{selected_option_ids:['explore']}),null).valid,false));
test('Comparison rejects a dropped or invented cell',()=>{const r=get('compare');r.content_blocks[1].rows[0].cells.pop();assert.equal(validateProtocol(r).protocolAccepted,false);});
test('Mobile comparison labels preserve every column',()=>{const html=renderToStaticMarkup(React.createElement(ProtocolV13Renderer,{data:get('compare')}));for(const label of ['Part-time study','Work trial','Self-study'])assert.ok(html.includes(`data-label="${label}"`));});
test('Copy and speech use visible content only',()=>{const text=responseToReadableText(get('compare'));assert.match(text,/Part-time study/);assert.doesNotMatch(text,/schema_version|security_breach_count|user_confidence|question_id/);assert.match(responseToReadableText(get('text')),/What is one activity/);});
test('Rejected JSON is never projected as prose',()=>assert.equal(responseToReadableText('{"state":"private"}'),'This response could not be displayed. Please try again.'));
test('Missing handoff labels repaired without inventing user data',()=>{const r=get('location');r.interaction.question='';r.interaction.question_id='';applyPresentationDefaults(r,'turn-1');assert.equal(validateProtocol(r).protocolAccepted,true);assert.equal(r.interaction.question_id,'request-details-turn-1');assert.deepEqual(r.rmo_readiness.missing_inputs,['location','residency']);});
test('Location choice repaired to typed field',()=>{const r=get('location');r.interaction.fields[0].input_type='single_select';applyPresentationDefaults(r,'turn-2');assert.equal(r.interaction.fields[0].input_type,'australian_location');assert.equal(validateProtocol(r).protocolAccepted,true);});
test('Empty ordinary AI question stays rejected',()=>{const r=get('text');r.interaction.question='';applyPresentationDefaults(r,'turn-3');assert.equal(validateProtocol(r).protocolAccepted,false);});
test('Previously submitted location is prefilled when a form reopens',()=>{const html=renderToStaticMarkup(React.createElement(ProtocolInteraction,{interaction:get('location').interaction,initialFields:{location:'Geelong, VIC',residency:'Domestic'},onInteract:async()=>true}));assert.match(html,/value="Geelong, VIC"/);assert.match(html,/value="Domestic" selected/);});
test('Model status does not claim that a request was completed',()=>{const r=makeResponse();r.content_blocks[0]={id:'summary',type:'list',title:'Draft summary',text:'',level:'none',variant:'default',columns:[],rows:[],items:[{id:'location',title:'Location',text:'Geelong',value:'',status:'complete'}]};const html=renderToStaticMarkup(React.createElement(ProtocolV13Renderer,{data:r}));assert.doesNotMatch(html,/>complete</);assert.match(html,/Geelong/);});
console.log(`${checks} experience checks passed.`);
