import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {pathwayFixture,pathwayReportFixture} from './mini-pathway-fixture';
import {miniPathwayPanelResponse} from '../src/miniPathway/presentation';
import {choosePathwayHint,decideMiniPathway,currentPathwaySource,alreadyHelpedInLowEpisode} from '../src/miniPathway/policy';
import {MiniPathwayService,validateMiniPathwayOutput} from '../src/miniPathway/service';
const hint=choosePathwayHint([{id:'pathway',score:.8},{id:'other',score:.2}]);
for(const score of [0,25,39])assert.equal(decideMiniPathway(pathwayFixture(score),'Help me choose a career',hint).action,'automatic');
for(const score of [40,69,70,100,-1])assert.equal(decideMiniPathway(pathwayFixture(score),'Help me choose a career',hint).action,'offer');
for(const score of [-2,101,NaN])assert.equal(decideMiniPathway(pathwayFixture(score),'Help me choose a career',hint).action,'none');
for(const text of ['Stop','No more suggestions','Do not suggest anything','No pathway','This is an emergency'])assert.equal(decideMiniPathway(pathwayFixture(),text,hint).action,'none');
assert.equal(decideMiniPathway(pathwayFixture(),'Choose a career',{status:'abstained',reason:'uncertain'}).action,'none');
assert.equal(choosePathwayHint([{id:'pathway',score:.7},{id:'other',score:.69}]).status,'abstained');
assert.equal(choosePathwayHint([{id:'pathway',score:NaN},{id:'other',score:.2}]).status,'abstained');
assert.equal(decideMiniPathway(pathwayFixture(),'Choose a career',hint,true).action,'offer');
const messages:any[]=[{id:'u1',role:'user',content:'I am unsure which career to choose. Help me compare possible pathways.'},{id:'a1',role:'assistant',content:JSON.stringify(pathwayFixture()),structuredResponse:pathwayFixture()}];
assert.ok(currentPathwaySource(messages,'a1'));
assert.equal(currentPathwaySource([...messages,{id:'u2',role:'user',content:'Stop'}],'a1'),null);
assert.equal(currentPathwaySource([{...messages[1],streamStopped:true}],'a1'),null);
assert.equal(alreadyHelpedInLowEpisode(messages,[{sourceMessageId:'a1'}]),true);
assert.equal(alreadyHelpedInLowEpisode([...messages,{id:'a2',role:'assistant',content:JSON.stringify(pathwayFixture(75))}],[{sourceMessageId:'a1'}]),false);
const newTopic=pathwayFixture(20);newTopic.state.user_confidence.reason_codes=['NEW_TOPIC_RESET','GOAL_UNCLEAR'];
assert.equal(alreadyHelpedInLowEpisode([...messages,{id:'a2',role:'assistant',content:JSON.stringify(newTopic)}],[{sourceMessageId:'a1'}]),false);
const question=pathwayFixture();question.current_mode='A_CONVERSATION';question.interaction={...question.interaction,kind:'question',input_type:'text',question_id:'q1',question:'Which activity interests you?'};
assert.equal(decideMiniPathway(question,'Choose a career',hint).action,'automatic');
assert.throws(()=>validateMiniPathwayOutput(question));
assert.throws(()=>validateMiniPathwayOutput({...pathwayFixture(),content_blocks:[]}));
assert.ok(validateMiniPathwayOutput(pathwayFixture()));
const wide=pathwayFixture();wide.content_blocks.push({id:'compare',type:'comparison',level:'none',variant:'default',title:'Two routes',text:'Compare the practical differences.',items:[],columns:[{key:'factor',label:'Factor'},{key:'a',label:'IT'},{key:'b',label:'Design'}],rows:[{id:'r1',cells:[{key:'factor',value:'First step'},{key:'a',value:'Try a support lab'},{key:'b',value:'Try a design exercise'}]}]});
const projected=miniPathwayPanelResponse(wide);
assert.equal(projected.content_blocks.filter(b=>b.type==='comparison').length,1);
assert.deepEqual(projected.content_blocks.find(b=>b.type==='comparison')?.rows,wide.content_blocks.at(-1).rows);
assert.equal(projected.content_blocks.find(b=>b.type==='comparison')?.text,'');
for(const phrase of ['Two routes','Compare the practical differences.','IT','Design','First step','Try a support lab','Try a design exercise'])assert.ok(JSON.stringify(projected.content_blocks).includes(phrase));
assert.equal(wide.content_blocks.at(-1).type,'comparison');
const dir=await fs.mkdtemp(path.join(os.tmpdir(),'yuzee-mini-pathway-'));
const mockAI=(respond:(req:any)=>Promise<any>)=>({models:{generateContentStream:async function*(req:any){
 const result=await respond(req);
 yield {candidates:[{...result.candidates?.[0],content:{parts:[{text:result.text}]}}],usageMetadata:result.usageMetadata};
}}}) as any;
let calls=0,logged=0,requests:any[]=[];
const ai=mockAI(async(req:any)=>{calls++;requests.push(req);return {text:JSON.stringify(pathwayReportFixture()),candidates:[{finishReason:'STOP'}],usageMetadata:{promptTokenCount:10,candidatesTokenCount:20}};});
const service=new MiniPathwayService(()=>ai,path.join(dir,'runs.json'),()=>logged++);
const conv={id:'test',model:'test-gemini',messages};
const request={mode:'automatic',sourceMessageId:'a1',hint,location:''};
const signal=new AbortController().signal;
const first=await service.generate(conv,request,signal,()=>{},()=>true);
assert.equal(first.status,'complete');assert.equal(calls,1);assert.equal(logged,1);
assert.match(requests[0].config.systemInstruction,/SYSTEM DIRECTIVE: YUZEE AI ASSISTANT ENGINE/);
assert.match(requests[0].config.systemInstruction,/TRUSTED SIDE-PANEL RUNTIME ADAPTER/);
assert.match(requests[0].config.systemInstruction,/FORMAL REPORT DEPTH PARITY/);
assert.doesNotMatch(requests[0].config.systemInstruction,/Prefer a compact overview/);
assert.equal(requests[0].config.maxOutputTokens,24000);
assert.match(requests[0].contents,/I am unsure which career/);
assert.equal(JSON.parse(requests[0].contents).runtime_metadata.user_entered_location,'');
assert.equal((await service.generate(conv,request,signal,()=>{},()=>true)).id,first.id);assert.equal(calls,1);assert.equal(logged,1);
const high={...conv,id:'high',messages:[messages[0],{...messages[1],content:JSON.stringify(pathwayFixture(80)),structuredResponse:pathwayFixture(80)}]};
await assert.rejects(service.generate(high,request,signal,()=>{},()=>true),/optional/);
assert.equal((await service.generate(high,{...request,mode:'manual'},signal,()=>{},()=>true)).status,'complete');
await assert.rejects(service.generate({...conv,id:'forged'}, {...request,hint:{status:'selected',score:.2,margin:.1}},signal,()=>{},()=>true),/not relevant/);
await assert.rejects(service.generate({...conv,id:'stale'},request,signal,()=>{},()=>false),/stopped/);
let release:(x:any)=>void=()=>{};
const waiting=mockAI(()=>new Promise(r=>release=r));
const concurrent=new MiniPathwayService(()=>waiting,path.join(dir,'concurrent.json'));
const inFlight=concurrent.generate(conv,request,signal,()=>{},()=>true);
while(!(await concurrent.list(conv.id)).length)await new Promise(r=>setTimeout(r,5));
await assert.rejects(concurrent.generate(conv,{...request,mode:'manual'},signal,()=>{},()=>true),/already being prepared/);
release({text:JSON.stringify(pathwayReportFixture()),candidates:[{finishReason:'STOP'}]});await inFlight;
const broken=new MiniPathwayService(()=>mockAI(async()=>({text:'{}',candidates:[{finishReason:'MAX_TOKENS'}]})),path.join(dir,'broken.json'));
await assert.rejects(broken.generate(conv,request,signal,()=>{},()=>true),/incomplete/);
assert.equal((await broken.list(conv.id))[0].status,'error');
await assert.rejects(broken.generate(conv,request,signal,()=>{},()=>true),/optional/);
let isCurrent=true;
const changed=new MiniPathwayService(()=>mockAI(async()=>{isCurrent=false;return {text:JSON.stringify(pathwayFixture()),candidates:[{finishReason:'STOP'}]};}),path.join(dir,'changed.json'));
await assert.rejects(changed.generate(conv,request,signal,()=>{},()=>isCurrent),/stopped/);
assert.equal((await changed.list(conv.id))[0].status,'error');
const cancelled=new AbortController();cancelled.abort();
await assert.rejects(service.generate({...conv,id:'cancelled'},request,cancelled.signal,()=>{},()=>true),/stopped/);
let repairCalls=0;const repairRequests:any[]=[];
const repair=new MiniPathwayService(()=>mockAI(async(req:any)=>{
 repairRequests.push(req);const report=pathwayReportFixture();
 if(repairCalls++===0)report.content_blocks=report.content_blocks.filter((b:any)=>b.id!=='route-summary-r1-timeline');
 return {text:JSON.stringify(report),candidates:[{finishReason:'STOP'}]};
}),path.join(dir,'repair.json'));
assert.equal((await repair.generate({...conv,id:'repair'},request,signal,()=>{},()=>true)).status,'complete');
assert.equal(repairCalls,2);
assert.match(JSON.parse(repairRequests[1].contents).validation_issues.join(),/route-summary-r1-timeline/);
await service.remove('test');assert.equal((await service.list('test')).length,0);
await fs.rm(dir,{recursive:true,force:true});
console.log('PASS confidence boundaries, unknown/relevance/safety, active Quiz separation, cache, concurrency, stale requests, source prompt, no automatic retry loops, invalid output and persistence.');
