import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {learningTypesIn,learningToneIn} from '../src/miniPathway/learningTypes';
import {PathwayLearningCues} from '../src/components/PathwayLearningCues';
import {GuidanceList} from '../src/components/GuidanceList';
import {pathwayReportFixture} from './mini-pathway-fixture';
const ids=(s:string)=>learningTypesIn(s).map(t=>t.id);
assert.deepEqual(ids('Graduate Diploma and Advanced Diploma'),['graddip','advanced']);
assert.deepEqual(ids('Certificate III, Cert II, Certificate IV'),['cert3','cert2','cert4']);
assert.deepEqual(ids('Cert 3 then Certificate III'),['cert3']);
assert.deepEqual(ids('Undergraduate Certificate and Graduate Certificate'),['undergrad','gradcert']);
assert.deepEqual(ids('Bachelor Honours Degree'),['honours']);
assert.deepEqual(ids('Bachelor of Nursing and Masters Degree'),['bachelor','masters']);
assert.deepEqual(ids('Year 3, Stage 4, 12 weeks, pre-apprenticeship'),[]);
assert.deepEqual(ids('Diploma to Bachelor degree'),['diploma','bachelor']);
assert.equal(learningToneIn('Certificate II then Certificate III'),undefined);
assert.equal(learningTypesIn('short course')[0].level,'Level not established');
assert.equal(learningTypesIn('Undergraduate Certificate')[0].level,'Covers AQF 5–7');
assert.deepEqual(ids('Industry / vendor certification'),['industry']);
const html=renderToStaticMarkup(<PathwayLearningCues text="Certificate II"/>);
assert.match(html,/AQF 2/);assert.match(html,/<details/);assert.match(html,/What to check/);
const block={...pathwayReportFixture().content_blocks[0],type:'steps' as const,items:[{id:'x',title:'Certificate II',text:'Explore training',value:'',status:'neutral' as const}]};
assert.doesNotMatch(renderToStaticMarkup(<GuidanceList block={block}/>),/pathway-learning-cue/);
assert.match(renderToStaticMarkup(<GuidanceList block={block} pathwayLearningCues/>),/data-learning-tone="level2"/);
console.log('PASS: specific qualification levels, overlapping names, mixed routes, no inferred level from stages/pre-apprenticeship, expandable explanations, and main-chat isolation.');
