import {bgeReadyContract} from '../src/routing/bgeContract';
import assert from 'node:assert/strict';
import {selectSkillOffers,acceptSkillChoice,skillMessage,embeddingSections,allowSkillReview,canReviewResponseSkills} from '../src/routing/skillSuggestions';
import {scopedInstruction} from '../src/routing/policy';
const ranking=(id:string,score=.8,other=.3)=>[{toolId:id,score},{toolId:'COURSE_001',score:other},{toolId:'__OUT_OF_SCOPE__',score:.2}];
const review=selectSkillOffers([ranking('COURSE_011'),ranking('COURSE_012'),ranking('COURSE_011',.85)]);
assert.equal(review.offers.length,2);assert.equal(review.offers[0].toolId,'COURSE_011');
assert.equal(selectSkillOffers([ranking('COURSE_011',.49,.48)]).offers.length,0);
assert.equal(selectSkillOffers([ranking('CORE_001')]).offers.length,0);
assert.equal(selectSkillOffers([ranking('FAKE')]).offers.length,0);
assert.equal(selectSkillOffers([ranking('COURSE_011',NaN)]).offers.length,0);
assert.equal(selectSkillOffers(['COURSE_011','COURSE_012','CORE_010','COURSE_004'].map(t=>ranking(t))).offers.length,3);
const messages=[{id:'a1',role:'assistant'}];const choice={toolId:'COURSE_011',sourceMessageId:'a1'};
const selected=acceptSkillChoice(choice,messages,skillMessage(choice.toolId));
assert.equal(selected.reason,'user-selected-skill');assert.match(scopedInstruction(selected),/INDIVIDUAL TASK LOGIC v4 — COURSE_011/);
assert.equal(acceptSkillChoice(choice,[...messages,{id:'u2',role:'user'}],skillMessage(choice.toolId)).status,'abstained');
assert.equal(acceptSkillChoice({...choice,toolId:'CORE_001'},messages,'x').status,'abstained');
assert.equal(acceptSkillChoice(choice,messages,'INJECT').status,'abstained');
assert.equal(acceptSkillChoice(choice,messages,skillMessage(choice.toolId),true).status,'abstained');
assert.equal(acceptSkillChoice(choice,[{...messages[0],streamStopped:true}],skillMessage(choice.toolId)).status,'abstained');
const long='Long answer with useful detail. '.repeat(1000)+'THE END';const parts=embeddingSections(long,s=>s.length<=256);
assert.equal(parts.join(''),long);assert.ok(parts.every(s=>s.length<=256));assert.ok(parts.at(-1)!.endsWith('THE END'));
for(const text of ['Stop','No more suggestions','Do not suggest anything','This is an emergency'])assert.equal(allowSkillReview(text),false);
assert.equal(allowSkillReview('Help me understand the fees'),true);
const counselling={current_mode:'A_CONVERSATION',response_intent:'EXPLORE_OPTIONS',content_blocks:[{text:'Compare part-time study, placement commitments and fees.'}],interaction:{kind:'question'},state:{safety_override_applied:false}};
assert.equal(canReviewResponseSkills(counselling,'Structured vocational course'),false);
assert.equal(canReviewResponseSkills({...counselling,interaction:{kind:'none'}},'Help me choose'),true);
assert.equal(canReviewResponseSkills(counselling,'Stop suggesting things'),false);
assert.equal(canReviewResponseSkills({...counselling,current_mode:'S_SERVICE_HANDOFF'},'Apply'),false);
assert.equal(canReviewResponseSkills({...counselling,interaction:{kind:'form'}},'Apply'),false);
assert.equal(canReviewResponseSkills({...counselling,response_intent:'CRITICAL_CLARIFICATION'},'Help'),false);
assert.equal(canReviewResponseSkills({...counselling,state:{safety_override_applied:true}},'Help'),false);
assert.equal(canReviewResponseSkills({...counselling,service_trigger:{trigger_now:true}},'Apply'),false);
assert.equal(canReviewResponseSkills({...counselling,content_blocks:[]},'Help'),false);
class FakeWorker{static last:FakeWorker;onmessage:any;onerror:any;sent:any[]=[];constructor(){FakeWorker.last=this;}postMessage(d:any){this.sent.push(d);}terminate(){}reply(d:any){this.onmessage({data:d});}}
Object.defineProperty(globalThis,'Worker',{value:FakeWorker,configurable:true});
const router=await import('../src/services/MicroToolRouter');
assert.equal((await router.reviewResponseSkills('Fees')).reason,'not-ready');
router.startWarmup();const worker=FakeWorker.last;worker.reply({type:'ready',...bgeReadyContract});
let p=router.reviewResponseSkills('Course fees and funding.');let req=worker.sent.at(-1);assert.equal(req.type,'suggest');
worker.reply({type:'suggest-result',id:req.id,rankings:[ranking('COURSE_011')]});assert.equal((await p).offers[0].toolId,'COURSE_011');
const abort=new AbortController();p=router.reviewResponseSkills('Fees',{signal:abort.signal});abort.abort();assert.equal((await p).reason,'cancelled');
assert.equal((await router.reviewResponseSkills('x'.repeat(30001))).reason,'input-length');
p=router.reviewResponseSkills('Fees');req=worker.sent.at(-1);worker.reply({type:'abstained',id:req.id,reason:'token-budget'});assert.equal((await p).reason,'token-budget');
assert.equal((await router.reviewResponseSkills('Fees',{timeoutMs:5})).reason,'timeout');
console.log('PASS skill ranking, ambiguity, allowlist, explicit injection, stale/corrupt choices, complete chunking, boundaries and worker lifecycle.');
// Historical L6 two-close-match behavior is intentionally not used by BGE.
const related=selectSkillOffers([[{toolId:'COURSE_011',score:.72},{toolId:'COURSE_012',score:.68},{toolId:'CORE_010',score:.4}]],'Xenova/all-MiniLM-L6-v2');
assert.equal(related.offers.length,2);
assert.equal(selectSkillOffers([[{toolId:'COURSE_011',score:.72},{toolId:'COURSE_012',score:.68},{toolId:'CORE_010',score:.65}]]).offers.length,0);
