import assert from 'node:assert/strict';
import {AutoTokenizer,env} from '@huggingface/transformers';
import {suggestionIndex} from '../src/routing/suggestionIndex';
import {checkEmbeddingInput} from '../src/routing/tokenBudget';
import {isTopicMenu,selectedTopic,acceptTopicRoute,suggestionText} from '../src/routing/skillSuggestions';
import {loadHelpEvidence,helpEvidenceInstruction,outdatedHelpClaim} from '../src/services/HelpEvidence';
const menu={kind:'question',input_type:'single_select',question:'Which aspect of your study planning would you like to focus on next?',options:[{id:'hecs',label:'HECS-HELP & Repayment Rules',description:'Loan indexation and repayment thresholds.'}]};
const event={userEvent:{interaction:{selected_option_ids:['hecs']}}};
assert.equal(isTopicMenu(menu),true);assert.match(selectedTopic(menu,event),/HECS/);
assert.equal(isTopicMenu({...menu,question:'What is your residency status?'}),false);
assert.equal(selectedTopic(menu,{userEvent:{interaction:{selected_option_ids:['fake']}}}),'');
const route={status:'selected',modelId:'Xenova/bge-small-en-v1.5',calibrationVersion:'bge-calibrated-v1',routingFlow:'topic',domainMargin:.2,toolId:'COURSE_011',score:.8,margin:.15,version:'minilm-guarded-v1'};
assert.equal(acceptTopicRoute(route,menu,event).reason,'user-selected-topic');
assert.equal(acceptTopicRoute({...route,toolId:'CORE_001'},menu,event).status,'abstained');
assert.equal(acceptTopicRoute({...route,score:.2},menu,event).status,'abstained');
assert.equal(acceptTopicRoute(route,{...menu,question:'Which course have you chosen?'},event).status,'abstained');
const input=suggestionText({content_blocks:[{title:'Study costs',text:'Tuition and funding.',items:[{title:'Placement',text:'Travel and equipment.'}]}],interaction:{recommended_actions:[]}},['Nursing','Domestic']);
assert.match(input,/Study costs\. Placement\. Travel/);assert.match(input,/Nursing\. Domestic/);
env.cacheDir='./data/minilm-cache';const tokenizer=await AutoTokenizer.from_pretrained('Xenova/all-MiniLM-L6-v2',{local_files_only:true});
assert.equal(new Set(suggestionIndex.map(s=>s.toolId)).size,103);
assert.ok(suggestionIndex.every(s=>checkEmbeddingInput(tokenizer,s.text).fits));
assert.equal((await loadHelpEvidence((async()=>{throw Error('offline');}) as any)).status,'unavailable');
assert.equal((await loadHelpEvidence((async()=>({ok:true,text:async()=>'<p>changed layout</p>'})) as any)).status,'unavailable');
const evidence=await loadHelpEvidence((async()=>({ok:true,text:async()=>'<p>The minimum repayment threshold changed in 2025-26. Repayments only on income above the threshold. Who benefited?</p>'})) as any);
assert.equal(evidence.status,'retrieved');assert.match(helpEvidenceInstruction(evidence),/2025–26 scope/);
assert.match(helpEvidenceInstruction(),/No current HELP source was retrieved/);
assert.equal(outdatedHelpClaim('HECS-HELP repayment rates start at 1% and go up.'),true);
assert.equal(outdatedHelpClaim('HECS-HELP uses marginal repayments above the relevant threshold.'),false);
console.log('PASS 103-tool index/token checks, topic-vs-intake routing, forged choices, grouped context and HELP evidence fail-closed checks.');
