import json,html
from pathlib import Path
root=Path(__file__).resolve().parents[1]
read=lambda p: json.loads((root/p).read_text())
esc=lambda s:html.escape(str(s))
data=read('output/bge-calibration/heldout-results.json'); browser=read('output/bge-calibration/browser-summary.json'); profile=read('src/routing/bgeCalibration.json'); content=read('src/routing/bgeSkillContent.json'); regress=read('output/bge-calibration/regression.json'); smoke=read('output/bge-calibration/live-smoke.json')
byid={r['expected']:r for r in data['results'][-1]['skills']}
registry={r['id']:r for r in read('src/routing/microtools.json')}
def table(head,rows):
 return '<div class="scroll"><table><thead><tr>'+''.join('<th scope="col">'+esc(x)+'</th>' for x in head)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(x)+'</td>' for x in r)+'</tr>' for r in rows)+'</tbody></table></div>'
rows=[]
for t in content:
 r=byid[t['id']];d=r['decision']; result='Selected correctly' if d.get('toolId')==t['id'] else 'Left with Gemini: '+d['reason'] if d['status']=='abstained' else 'Different skill: '+d['toolId']
 rows.append('<tr><td>'+esc(t['id'])+'<br><strong>'+esc(registry[t['id']]['name'])+'</strong></td><td>'+esc(t['text'])+'</td><td>'+esc(result)+'</td></tr>')
failed=sum(r['exitCode']!=0 for r in regress)
source=smoke.get('saved',{}).get('messages',[{}])[-1];usage=source.get('telemetry',{}).get('usage',{});validation=next((e['data'] for e in smoke.get('events',[]) if e['type']=='validation'),{})
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Yuzee — BGE calibration and 103 skills</title><style>
:root{font-family:system-ui,-apple-system,sans-serif;color:#243047;background:#fff}body{max-width:1120px;margin:48px auto;padding:0 24px 80px;line-height:1.65}h1{font-size:36px;line-height:1.2;color:#182238;max-width:900px}h2{font-size:23px;margin:40px 0 10px}h3{font-size:18px}p{max-width:900px}a{color:#6540b7}small,.muted{color:#627088}.lead{font-size:20px}.note{border-left:3px solid #9875d0;padding-left:18px}.scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;font-size:14px}th{text-align:left;background:#f5f3fa;color:#3d3260}th,td{padding:12px 14px;border-bottom:1px solid #e3e6ed;vertical-align:top}tbody tr:hover{background:#faf9fc}input{width:min(100%,540px);box-sizing:border-box;font:inherit;padding:10px 14px;border:1px solid #b5bac9;border-radius:6px}details{padding:14px 0;border-bottom:1px solid #e3e6ed}summary{cursor:pointer;font-weight:650}code{font-size:.9em}nav{display:flex;flex-wrap:wrap;gap:20px}li{margin:7px 0}@media(max-width:650px){body{margin-top:28px;padding:0 16px 48px}h1{font-size:28px}th,td{padding:9px;min-width:100px}}@media print{input,nav{display:none}body{max-width:none;margin:0;font-size:10pt}h2{break-after:avoid}tr{break-inside:avoid}details{display:block}}</style></head><body>
<p class="muted">Yuzee AI Lab · 17 September 2026 · BGE calibration v1</p>
<h1>BGE now has its own matching content and selection rules</h1>
<p class="lead">The browser test selected 40 correct skills and one wrong skill across 103 new requests. L6 selected 19 correctly and three incorrectly on the same requests.</p>
<p>BGE is integrated and selected in the local chat for testing. The application default remains L6. BGE is stronger at accepted skill routing in this evaluation; it has not proved better at every part of the conversation.</p>
<nav><a href="#browser">Browser results</a><a href="#flow">How the conversation works</a><a href="#content">All 103 descriptions</a><a href="#limits">Remaining gaps</a></nav>
<h2 id="browser">Actual browser results</h2>
<p>Production worker, quantized weights, one browser thread. The examples were frozen before evaluation. “No selection” means Gemini continues without an automatically chosen skill.</p>
'''
page+=table(['Model','Correct / 103','Wrong / 103','No selection','Correct first match','Useful offers / 24','Wrong offers','Median / p95'],[[s['label'],s['correct'],s['wrong'],s['abstained'],s['top1'],s['suggestionsWithRelevant'],s['irrelevantOffers'],f"{s['medianMs']:.1f} / {s['p95Ms']:.1f} ms"] for s in browser['results']])
page+='''<p>Both rejected all 24 unrelated or unsuitable requests for routing and offers. BGE selected 41 correct topics and one wrong topic from navigation choices; L6 selected 23 correct and four wrong. The browser made 620 worker requests across both models, including unchanged input-needs and pathway checks.</p>
<h2>Before and after BGE calibration</h2><p>This comparison uses the native CPU runtime on the same new examples. CPU and browser scores differ slightly, so these figures must not be mixed with the browser table.</p>'''
page+=table(['Configuration','Correct routes','Wrong routes','No selection','Useful offers / 24','Wrong offers'],[[s['summary'][k] for k in ['label','correct','wrong','abstained','suggestionsWithRelevant','irrelevantOffers']] for s in data['results']])
page+='''<h2>What changed</h2><ul><li>103 explicit matching descriptions distinguish the object, the requested task and its intended result. BGE compares both the new description and the original catalogue description for each skill.</li><li>An additional background index represents unrelated, vague and unsuitable requests. A relevant skill must beat that competing interpretation.</li><li>Automatic routing, navigation topics and optional suggestions have explicit model profiles. The server validates the same profile used by the browser.</li><li>The existing detailed Gemini skill instructions, learning-depth guidance and input contracts remain in place. Matching content helps choose the instruction; it is not the instruction that teaches or counsels the user.</li><li>The CSV includes the matching content for all 103 skills and the corresponding integration rules. Its existing prompts and input guidance are preserved.</li></ul>
<h2>Calibrated selection rules</h2><p>These are similarity cut-offs, not percentages of certainty. The calibration search required at least 95% accepted precision and no accepted negative examples on development data, then maximised useful selections.</p>'''
page+=table(['Flow','Minimum similarity','Lead over next skill','Lead over unrelated interpretation'],[[k,profile[k]['score'],profile[k]['margin'],profile[k]['domainMargin']] for k in ['route','topic','suggestion']])
page+='''<p>BGE offers at most one matching skill per response section, then deduplicates and displays at most three overall. It does not use L6’s fallback that offers two close matches. Uncertain cases stay with Gemini.</p>
<h2 id="flow">How the conversation works</h2>'''
page+=table(['Situation','What happens','What the user sees'],[
 ['An explicit @Oala request or navigation choice has a clear skill match','BGE ranks the request. The server checks the model profile and injects only the approved skill guidance.','Gemini answers with the relevant skill’s depth and format.'],
 ['Gemini finishes an answer with no active question','BGE reviews meaningful response sections and recent context. Only separated, relevant matches become offers.','Optional skills beneath that response.'],
 ['Gemini asks a necessary question','The existing interaction remains active and skill offers are suppressed.','One clear question, without competing recommendations.'],
 ['The user chooses a skill','The server checks the source response and retrieves the approved prompt, depth guidance and input contract.','A deeper Gemini answer using known conversation details.'],
 ['Important information is missing','The skill contract tells Gemini to use existing context, give useful general guidance and ask only for material missing information.','A focused clarification, not the same generic intake form.'],
 ['The request is vague, unrelated or ambiguous','The routing model abstains. It does not insert an arbitrary task or invent missing context.','The main counsellor continues the conversation.'],
 ['Current facts are needed','The existing research flow must obtain sources. An embedding match does not count as evidence.','Known facts, unresolved details and an optional scoped lookup.'],
])
page+='<h2>End-to-end chat check</h2><p>A new synthetic conversation asked whether a diploma and bachelor degree are at the same academic level. The local server accepted BGE’s <code>COURSE_003</code> selection and <code>bge-calibrated-v1</code> profile. The configured Gemini endpoint returned an explanation, comparison table, pathway note and follow-up question. The response passed both schema and semantic validation. This checks request-to-response integration, not the factual accuracy of every statement.</p>'
page+=f'<p>{len(regress)} automated test suites passed; failures: {failed}. Production build passed. The model-switch, source-message, profile, input-length, active-question and cancellation tests are included.</p>'
page+='''<h2 id="limits">What still needs improvement</h2><ul><li><strong>Coverage:</strong> BGE abstained on 62 of 103 browser requests. Some are valid tasks that still need stronger matching or context. A lack of a card is not a broken Gemini response.</li><li><strong>Company-role confusion:</strong> “What job families exist inside Australia Post beyond delivery drivers?” selected internal mobility instead of the company role map in the browser.</li><li><strong>Suggestions:</strong> BGE and L6 both found useful offers in 8 of 24 browser excerpts. On CPU, one course-sequencing excerpt was confused with recognition of prior learning. BGE has not established a consistent suggestion advantage over L6.</li><li><strong>Pathways:</strong> unchanged BGE pathway detection passed 12/16 cases versus L6’s 14/16. This change calibrates skills, not the pathway or input-needs classifiers.</li><li><strong>Context:</strong> existing short-request, correction and multi-question guards can suppress valid tasks. This calibration did not redesign those shared guards.</li><li><strong>Evidence:</strong> tests are synthetic, written by the same author as the descriptors. They were not used to retune the frozen profile, but independent real-user evaluation is still needed. One live Gemini check does not certify all 103 generated outputs.</li></ul>
<p class="note">Next evaluation should use independently labelled real conversations, particularly ambiguous company, curriculum and course-credit requests. Keep today’s held-out examples as regression tests; use new untouched examples to assess any further tuning.</p>
<h2 id="content">All 103 matching descriptions</h2><p>These are semantic matching instructions. The result column refers to the new CPU test for that skill, not a guarantee across all phrasings. The existing detailed answer prompts remain the source of Gemini’s counselling guidance.</p>
<label for="search">Find a skill or topic</label><br><input id="search" type="search" placeholder="For example: fees, placements, company"><p id="count" class="muted" aria-live="polite">103 skills</p>
<div class="scroll"><table id="skills"><thead><tr><th>Skill</th><th>BGE matching description</th><th>CPU test result</th></tr></thead><tbody>'''+''.join(rows)+'''</tbody></table></div>
<h2>Files and evidence</h2><ul><li><a href="../csv/yuzee_microtools_prompt_registry.csv">Updated skill registry CSV</a> — 162 records, 36 columns, including 103 BGE descriptions.</li><li><a href="../bge-calibration/browser-summary.json">Browser results and known mismatch</a></li><li><a href="../bge-calibration/heldout-results.json">Full native CPU case results</a></li><li><a href="../bge-calibration/calibration.json">Development calibration and selection rules</a></li><li><a href="../bge-calibration/evaluation-lock.json">Frozen evaluation hashes</a></li><li><a href="../bge-calibration/regression.json">Automated regression results</a></li></ul>
<script>const input=document.getElementById('search');input.addEventListener('input',()=>{let count=0;document.querySelectorAll('#skills tbody tr').forEach(row=>{row.hidden=!row.textContent.toLowerCase().includes(input.value.toLowerCase());if(!row.hidden)count++});document.getElementById('count').textContent=count+' skills';});</script></body></html>'''
(root/'output/html/Yuzee-BGE-Calibration.html').write_text(page)
print('Created BGE report with 103 searchable descriptions.')
